language: java
sudo: true
dist: trusty
jdk:
  - openjdk8
services:
  - docker
addons:
  sonarcloud:
    organization: "sorackb"
    token:
      secure: $SONAR_TOKEN
# Test & Build SpringBoot app
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install package sonar:sonar -Dsonar.projectKey=Sorackb_HealthcareInstitution
# Create Docker image for our app and push it to Dockerhub repository
after_success:
  - export COMMIT=${TRAVIS_COMMIT::7}
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose build
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG
# Allow Travis to help deploy the app on Heroku
deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: healthcare-institution
  on:
    tags: true